### ISSUE TITLE
Finer grained configuration to make index smaller & faster for large sites: by `linkTitle`, by `title`, by Headings Level 1 only, and etc.

### ISSUE THREAD

**Issue by FuadEfendi** [hugomods/search#253]
For large dictionary-like websites, containing terms with definitions, it makes sense to search by main term only and avoid search by sub-headings and content.
For example, searching by `linkTitle` only, completely avoiding all other parts of an article, will make the search index very small. Could be "expanded" to `title`, `description`, Heading Level 1, 2, etc. 
Applicable for professional dictionary-like websites and large websites in general.

**Comment by razonyang** [comment]
> searching by linkTitle only, completely avoiding all other parts of an article

TBD, but I don't have a proposal yet. Please describe your implementation below if you have any. Since the title is required and this request seems unusual, it will greatly impact the UI, PRs are also welcome.

> Could be "expanded" to title, description, Heading Level 1, 2, etc.

Headings and description (summary) make sense.

Btw, if your site is large, it's always recommended to use an online search serviceto save bandwidth, and improve the user experience, the client search need to download the large index.json from your server and index it locally, it really take time and bandwidth, especially to a large site.

**Comment by FuadEfendi** [comment]
Thanks; yes, I plan to integrate with Algolia, didn't have enough time yet... if JS search can index only main title (and ignore subtitles, text) it can make index size at least 10x smaller I hope.
But with Algolia it could be 1000x more powerful: stop-words, synonyms, word stemming, fuzzy search, auto error correction, and etc.; I did it a while ago (not very good UI, but index was Ok) but now I plan to find a way to integrate with hugomods/search.

**Comment by razonyang** [comment]
The linkTitle request will not be approved at this time.

For the other requests, please check the release notes of [v0.17.0](https://github.com/hugomods/search/releases/tag/v0.17.0) and the [docs](https://hugomods.com/search/configurations/).

If this index is still large, it might be time to move to an online service. The client-side JS implementation is not designed for large websites with millions of content.

**Comment by FuadEfendi** [comment]
Thanks for [v0.17.0](https://github.com/hugomods/search/releases/tag/v0.17.0) with new features; `index_heading` filter is really great to have even for 100-page sites with a unified page structure; this use case is not specific to large sites. 

JS is better than Algolia if we need to index only page titles.
